services:
  # Backend: Flask API
  - type: web
    name: chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    autoDeploy: true

  # Frontend: React.js App
  - type: web
    name: chatbot-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    staticPublishPath: build
    autoDeploy: true
